version: "3.8"
services:

  catalog-service:
    depends_on:
      - polar-postgres
    image: "vinyl-service"
    container_name: "vinyl-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vin-postgres:5432/vinyls_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  vin-postgres:
    image: "postgres:14.4"
    container_name: "vin-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vinyls_catalog